on: push

jobs:
    build:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v4
          with:
            submodules: recursive
        - uses: jurplel/install-qt-action@v4
        - uses: blinemedical/setup-gstreamer@v1.4.0
          with:
            version: "1.26.6"
        - run: cmake -B build -S .
        - run: cmake --build build
